name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install backend dependencies
        working-directory: "bloglist-backend"
        run: npm install
      - name: Check backend style
        working-directory: "bloglist-backend"
        run: npm run lint
      - name: Create env file
        working-directory: "bloglist-backend"
        run: |
          touch .env
          echo TEST_MONGODB_URI=mongodb://username:password@localhost:27017/test-fullstackopen-blog?authSource=admin >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo SECRET=${{ secrets.SECRET }} >> .env
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-username: username
          mongodb-password: password
          mongodb-db: test-fullstackopen-blog
      - name: Backend Tests
        working-directory: "bloglist-backend"
        run: npm test
      
      - name: Install frontend dependencies
        working-directory: "bloglist-frontend"
        run: npm install
      - name: Check frontend style
        working-directory: "bloglist-frontend"
        run: npm run lint
      - name: Build
        working-directory: "bloglist-frontend"
        run: npm run build
      - name: Frontend Tests
        working-directory: "bloglist-frontend"
        run: npm test

      - name: Install e2e dependencies
        working-directory: "bloglist-e2e"
        run: npm install
      - name: Run E2E Tests
        uses: BerniWittmann/background-server-action@v1
        with:
            command: cd ../bloglist-e2e && npm ci && npx playwright install --with-deps && npm test
            start: cd ../bloglist-server && npm run start:test
      - uses: actions/upload-artifact@v4
        if: ${{ ! cancelled() }}
        with:
          name: playwright-report
          path: playwright-repo/
          retention-days: 30
  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "#patch"